google_client_id = "mock-google-client-id"
google_client_secret = "mock-google-client-secret"
discord_client_id = "mock-discord-client-id"
discord_client_secret = "mock-discord-client-secret"
session_key = "0000000000000000000000000000000000000000000000000000000000000000"
